version: '3'

services:
  neuralclock-prod:
    build: 
      context: .
      dockerfile: Dockerfile
    image: neuralclock-repository
    container_name: NeuralClockAPP
    restart: always
    ports:
      - "80:4000"

  
